### ISSUE TITLE
bug: Found some errors on 5x version

### ISSUE THREAD

**Issue by ViacheslavBurlaka** [vime-js/vime#156] opened 2021-01-05 01:46 UTC
have some errors

1. when try to change dynamically src to another or just navigate to another link, have this error:
Uncaught TypeError: _a.destroy is not a function

2. some of my test hls stream videos have list of undefinedp playback quality
3. dbclick on fullscreen doesn't close fullscreen

version latest (5.0.19 + hls + react)

**Comment by mihar-22** [comment] 2021-01-05 02:04
Hey @ViacheslavBurlaka!

1. I need to look into this.
2. If you could share the HLS streams so I can test it.
3. I've merged a PR that fixes fullscreen, releasing soon.

In regards to styling you can simply set the CSS variables on the player you'd like to change. The documentation has a section on it https://vimejs.com/getting-started/styling.

```css
vm-player {
  /* CSS variables go here. */
}
```
You can find all CSS variables here: https://github.com/vime-js/vime/blob/master/core/src/themes/default.css

**Comment by ViacheslavBurlaka** [comment] 2021-01-05 02:11
@mihar-22  thanks for your quick response! 

2.  
<img width="530" alt="Снимок экрана 2021-01-05 в 04 11 24" src="https://user-images.githubusercontent.com/16492645/103598753-16768500-4f0c-11eb-9289-2d1af8f54336.png">

of course, that link has undefinedp playback qualities:
 https://meta.vcdn.biz/9a7c35dfade6804f040929ab8b084efb_megogo/vod/hls/b/450_900_1350_1500_2000_5000/u_sid/0/o/363861/u_uid/573447295/u_vod/4/u_device/briz_ua/u_devicekey/_briz_ua_web/u_srvc/131/te/1611320031/a/11/type.amlst/playlist.m3u8

**Comment by mihar-22** [comment] 2021-01-05 02:58
I think it might be because the playlist manifest doesn't specify a resolution on the streams. Here's an example: https://github.com/vime-js/media/blob/master/hls/index.m3u8.

`#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360"`

**Comment by mihar-22** [comment] 2021-01-05 21:55
I have to somehow fix this, TypeScript suddenly isn't transpiling optional chaining `?.` and Stencil doesn't let me change it. I'll look into it today.

**Comment by jonsadka** [comment] 2021-01-05 23:55
@mihar-22 I think it could be related to the most recent changes https://github.com/vime-js/vime/commit/4ce26ad3f6a8b34f3e549a4844048e2bafe4f1ef. I dont believe `es5` supports optional chaining

**Comment by djw12581** [comment] 2021-01-06 02:55
> 我必须以某种方式解决此问题，TypeScript突然没有转译可选链接，`?.`而Stencil不允许我更改它。我今天去研究。

?.  为 es-2020 语法 用新的 loader 试试呢

**Closed** 2021-01-06 03:12 UTC
Labels: bug

**Comment by mihar-22** [comment] 2021-01-06 03:13
Release is on the way right now to fix the `?.` problem. CI should release it in 5 minutes.

**Comment by ViacheslavBurlaka** [comment] 2021-01-06 09:38
another error, when click fullscreen and back
`Uncaught TypeError: _this$fullscreen2.destroy is not a function`

**Comment by jbjhjm** [comment] 2021-06-14 12:37
It's possible there is a regression in the current 5.0.31 builds. I'm experiencing the same untranspiled "?." issue again, see https://github.com/vime-js/vime/issues/209
